
include Makefile

MAIN=./MarDyn.cpp
SOURCES := $(filter-out $(MAIN),$(SOURCES))
CXXFLAGS+= -fPIC 

lib: .deps $(OBJECTS)
	$(CXX) $(LDFLAGS) -shared -Wl,-soname,Mardyn.so -lc -fp -o lib$(BINARY).so $(OBJECTS)
	$(CXX) $(LDFLAGS) -shared -Wl,-soname,libMardyn.so.1 -o libMardyn.so.1.0 $(OBJECTS)

