#!/bin/sh
#
rm -f ls1*
make -f Makefile.seq_deb.NVT.ts_ter clean
make -f Makefile.seq_deb.NVT.ts_ter
make -f Makefile.par_run.NVT.fl_ter clean
make -f Makefile.par_run.NVT.fl_ter
make -f Makefile.par_run.NVT.fl_LCQ clean
make -f Makefile.par_run.NVT.fl_LCQ
make -f Makefile.par_deb.NVT.ts_ter clean
make -f Makefile.par_deb.NVT.ts_ter
make -f Makefile.seq_run.NVT.ts_ter clean
make -f Makefile.seq_run.NVT.ts_ter
make -f Makefile.par_run.NVT.ts_ter clean
make -f Makefile.par_run.NVT.ts_ter
